### PR TITLE
(feat) Add the ability to handle apolloPrefetch with a request

### PR DESCRIPTION
**Pull request by Austio**
This feature is useful for many things.  A great example is short circuiting long running graphql requests to prevent the browser from hanging during the network request

```
new VueApollo({
    handleServerPrefetch(apolloPromises) {
      const shirtCircuit = new Promise((resolve, reject) => { setTimeout(resolve, 4000) })
      
      return Promise.race(apolloPromises, shortCircuit)
    }
})
```

### CODE REVIEW

**Comment by Austio** [comment]
@Akryum Do you have any thoughts on merging this in to allow tapping into these requests?

**Comment by Akryum** [comment]
Couldn't it be achieved using apollo links?

**Comment by Austio** [comment]
@Akryum have this on schedule to investigate with apollo-link

**Comment by glen-84** [comment]
@Akryum It looks like this should be closed as abandoned.

**Pull request closed without merging**
