### PR TITLE
Adding Spanish

### PR DESCRIPTION
**Pull request by alphacentauri82**

### CODE REVIEW

**Comment by Akryum** [comment]
@alphacentauri82 I think you need to merge dev and update the PR a bit! 😸

**Comment by alphacentauri82** [comment]
Will do!!

**Comment by Akryum** [comment]
:pray:

**Comment by alphacentauri82** [comment]
On the works! Give me a week and I will be done

**Comment by glen-84** [comment]
@Akryum It looks like this should be closed as abandoned.

**Pull request closed without merging**
