### PR TITLE
Apollo Client v3 migration

### PR DESCRIPTION
**Pull request by mlesin**
Can't wait for Apollo 3 support, decided to help you with that :)

During migration process, some dependencies were required to be bumped too, including @vue/composition-api 1.0.0-beta.6

### CODE REVIEW

**Comment by the-jackalope** [comment]
I'm not part of the project so don't want to interject with a review, but @mlesin I think that instead of importing from `@apollo/client` we'd want to import from `@apollo/client/core`, no?

There's a [section in the Apollo 3 docs](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#using-apollo-client-without-react) that specifies importing from `@apollo/client/core` avoids importing React.

Either way thanks for doing this - excited for `vue-apollo` to support Apollo 3!

**Comment by mlesin** [comment]
Thank you for noticing, @the-jackalope!
After I removed react dependency, it looks much cleaner now.

**Comment by brunomperes** [comment]
Awesome work @mlesin !

Are there pending tasks for this that we can help with or is it good to review/merge? 😄

**Comment by mlesin** [comment]
It is ready for review/merge.
The only thing left but I can't do is changes in chinese translation of docs because I don't understand chinese :)

**Comment by dmitry** [comment]
@Akryum what is the status of this project, is it temporarily suspended or closed? Can we go forward and merge this PR? Any help required?

**Comment by Akryum** [comment]
@mlesin Is there anything mssing from the current v4 branch that is added here? Could you rebase your branch please? 🙏  Thanks!

**Comment by mlesin** [comment]
@Akryum I didn't introduced any functionality here except pure port to apollo-3.
At first sight, you're implemented the same thing yourself, plus some additional changes. So I don't think there is any need to rebase this PR. 
I think it's safe to close it.

**Pull request closed without merging**
