### PR TITLE
Remove *.gql/*.graphql types

### PR DESCRIPTION
**Pull request by jbbr**
The `*.graphql` module declaration conflicts with similar declarations in many projects. And in my opinion it's out of the scope of this library. I will try to explain my reasoning:

Unfortunately TypeScript doesn't have an option to exclude types from NPM packages. So these these types are loaded without a way to opt-out.
But many projects might have different needs for *.graphql typings. e.g:

- Add specific modules for every `*.graphql` file
 The populare tool "Graphql Code Generator" can autogenerate imports for graphql-files, example here: https://graphql-code-generator.com/docs/plugins/typescript-graphql-files-modules#example 

- Allow named imports from `*.graphql`-files (e.g Queries & Mutations) using `graphql-tag/loader`:
  e.g `import { SomeQuery, AnotherQuery } from 'somefile.graphql'`.
  One way to allow this is by a simple any declaration:
  `declare module '*.graphql';`

- Not every typescript project has some loader configured to load `*.graphql`-files.
So having these types by default makes incorrect assumptions.

These kind of custom declarations are not possible when using vue-apollo 3.x due to this fixed type which is bundled with vue-apollo.

I propose to just remove the type file again and add docs which explain the situation.

### Failing example

```ts
import {SomeQuery} from 'somefile.graphql'

export default {
  apollo: {
    someQuery: {query: SomeQuery},
  },
}
```

Error:

```
ERROR in MyModule.vue(14,3):
 14:3 Module '"*.graphql"' has no exported member 'SomeQuery'. Did you mean to use 'import SomeQuery from "*.graphql"' instead?
  > 14 |   SomeQuery,
          |   ^
      15 | } from './somefile.graphql';
      16 |
```

### Workaround

Downgrade and pin `3.0.0-rc.7`. Packge json:
```json
"vue-apollo": "=3.0.0-rc.7",
```

### CODE REVIEW

**Comment by jbbr** [comment]
I know it's been a while, but I still think this is an issue and should be fixed - maybe in the 4.x version, as this might be considered a breaking change.

**Comment by Kocal** [comment]
Hi,

As a temporary workaround (I hope), I added the following lines in my `package.json`:
```json
{
  "scripts": {
    "postinstall": "rm node_modules/vue-apollo/types/gql.d.ts"
  }
}
```

**Comment by ferm10n** [comment]
I lost about a couple of hours today trying to hunt down why type defs couldn't be resolved for any .gql files because of this. It's all sorted out now, but it was quite frustrating finding the one commit that had automatically updated vue-apollo from 3.0.3 to 3.0.4 and broke our build.

I would have preferred this was included in 4.x as @jbbr suggested. I'm hoping greater care will be taken in future releases. That said, I appreciate the awesome work you guys are doing. Many thanks.

**Comment by MisterMilk24** [comment]
@ferm10n  Same thing for me, found at few days ago that the 3.0.4 caused me this problem. Are you aware of a workaround, since I prefer to keep my requests in .gql files even for the future?

**Pull request merged**
